# This file was generated by GoReleaser. DO NOT EDIT.
cask "clippy" do
  desc "Unified clipboard tool for macOS - a superset of pbcopy"
  homepage "https://github.com/neilberkman/clippy"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clippy"

  on_macos do
    on_intel do
      url "https://github.com/neilberkman/clippy/releases/download/v0.5.0/clippy_0.5.0_darwin_amd64.tar.gz"
      sha256 "029e076336a3fca0c0f639f96e93605b1559d1da60ec5035e1b98ce533b24608"
    end
    on_arm do
      url "https://github.com/neilberkman/clippy/releases/download/v0.5.0/clippy_0.5.0_darwin_arm64.tar.gz"
      sha256 "94b289f311d4572bd3d67217d87da172bfcca59ba1157d368beda921d6ccfdf0"
    end
  end

  # No zap stanza required
end
