# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clippy < Formula
  desc "Unified clipboard tool for macOS - a superset of pbcopy"
  homepage "https://github.com/neilberkman/clippy"
  version "0.9.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/neilberkman/clippy/releases/download/v0.9.1/clippy_0.9.1_darwin_amd64.tar.gz"
    sha256 "43905f052db45a58dd2d648f8402d6fe98137b3dc8aad04e61bdfbe3e4c89f04"

    def install
      bin.install "clippy"
      bin.install "pasty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/neilberkman/clippy/releases/download/v0.9.1/clippy_0.9.1_darwin_arm64.tar.gz"
    sha256 "e34091b9d30fc3f98152ec05ddcf2cb8551e55c8953129c0620cf21659333f17"

    def install
      bin.install "clippy"
      bin.install "pasty"
    end
  end

  test do
    system "#{bin}/clippy", "--version"
  end
end
