# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clippy < Formula
  desc "Unified clipboard tool for macOS - a superset of pbcopy"
  homepage "https://github.com/neilberkman/clippy"
  version "0.6.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/neilberkman/clippy/releases/download/v0.6.1/clippy_0.6.1_darwin_amd64.tar.gz"
    sha256 "6fc0a18f1724c17c8c456a664c411d6fa12e6dc5d65de9dd7f26c657b8a3ffd7"

    def install
      bin.install "clippy"
      bin.install "pasty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/neilberkman/clippy/releases/download/v0.6.1/clippy_0.6.1_darwin_arm64.tar.gz"
    sha256 "9df856beee21ce00921560811b90e9995d9be3c171cda89a75992a919df0d5c5"

    def install
      bin.install "clippy"
      bin.install "pasty"
    end
  end

  test do
    system "#{bin}/clippy", "--version"
  end
end
