# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clippy < Formula
  desc "Unified clipboard tool for macOS - a superset of pbcopy"
  homepage "https://github.com/neilberkman/clippy"
  version "1.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/neilberkman/clippy/releases/download/v1.3.0/clippy_1.3.0_darwin_amd64.tar.gz"
    sha256 "5622f1819cbd56fca1418721d5af09dca8e9c2eb55d0a561aba7c30f2a076fba"

    def install
      bin.install "clippy"
      bin.install "pasty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/neilberkman/clippy/releases/download/v1.3.0/clippy_1.3.0_darwin_arm64.tar.gz"
    sha256 "11e1ab11b49955d407ff5aa82b65852e5a6da3e1cc2bcd4856a1fcdcc35d6756"

    def install
      bin.install "clippy"
      bin.install "pasty"
    end
  end

  test do
    system "#{bin}/clippy", "--version"
  end
end
